export const COLLPSE_CHANGE = 'COLLPSE_CHANGE';
export const COLLPSE_OPEN_DRAWER = 'COLLPSE_OPEN_DRAWER';
export const CHANGE_OPEN_KEYS = 'CHANGE_OPEN_KEYS';
export const TOGGLE_ALL = 'TOGGLE_ALL';
export const CHANGE_CURRENT = 'CHANGE_CURRENT';
export const CLEAR_MENU = 'CLEAR_MENU';