export const GET_USER_INIT = 'GET_USER_INIT';
export const GET_USER_COMPLETE = 'GET_USER_COMPLETE';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const GET_USER_DETAILS_INIT = 'GET_USER_DETAILS_INIT';
export const GET_USER_DETAILS_COMPLETE = 'GET_USER_DETAILS_COMPLETE';
export const GET_USER_DETAILS_ERROR = 'GET_USER_DETAILS_ERROR';